# Generated by Django 5.2.4 on 2025-07-28 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tvchannels", "0004_alter_videofile_duration_seconds_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InjestJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("running", "Выполняется"),
                            ("completed", "Завершена"),
                            ("failed", "Ошибка"),
                            ("paused", "Приостановлена"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "scan_interval",
                    models.IntegerField(
                        default=300, verbose_name="Интервал сканирования (сек)"
                    ),
                ),
                (
                    "file_extensions",
                    models.CharField(
                        default="mp4,avi,mkv,mov,wmv,flv,webm,m4v,3gp,ts",
                        help_text="Через запятую",
                        max_length=200,
                        verbose_name="Расширения файлов",
                    ),
                ),
                (
                    "max_concurrent_transfers",
                    models.IntegerField(
                        default=3, verbose_name="Макс. одновременных операций"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "last_run",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последний запуск"
                    ),
                ),
                (
                    "next_run",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Следующий запуск"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Задача импорта",
                "verbose_name_plural": "Задачи импорта",
            },
        ),
        migrations.CreateModel(
            name="RemoteServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название сервера"),
                ),
                ("host", models.CharField(max_length=255, verbose_name="Хост")),
                ("port", models.IntegerField(default=22, verbose_name="Порт SSH")),
                (
                    "username",
                    models.CharField(max_length=100, verbose_name="Пользователь"),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        help_text="Или используйте ключ",
                        max_length=255,
                        verbose_name="Пароль",
                    ),
                ),
                (
                    "private_key_path",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Путь к приватному ключу",
                    ),
                ),
                (
                    "remote_directory",
                    models.CharField(
                        default="/media/videos/",
                        max_length=500,
                        verbose_name="Удаленная папка для поиска",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "connection_timeout",
                    models.IntegerField(
                        default=30, verbose_name="Таймаут соединения (сек)"
                    ),
                ),
                (
                    "last_connected",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последнее подключение"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Удаленный сервер",
                "verbose_name_plural": "Удаленные серверы",
            },
        ),
        migrations.CreateModel(
            name="FileImportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        max_length=500, verbose_name="Оригинальное имя файла"
                    ),
                ),
                (
                    "original_path",
                    models.CharField(max_length=1000, verbose_name="Оригинальный путь"),
                ),
                (
                    "new_filename",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Новое имя файла"
                    ),
                ),
                (
                    "new_path",
                    models.CharField(
                        blank=True, max_length=1000, verbose_name="Новый путь"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Размер файла (байты)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("discovered", "Обнаружен"),
                            ("processing", "Обрабатывается"),
                            ("imported", "Импортирован"),
                            ("renamed", "Переименован"),
                            ("failed", "Ошибка"),
                            ("skipped", "Пропущен"),
                        ],
                        default="discovered",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Сообщение об ошибке"),
                ),
                (
                    "processing_time",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Время обработки (сек)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "video_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tvchannels.videofile",
                        verbose_name="Видеофайл",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_logs",
                        to="injest.injestjob",
                        verbose_name="Задача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог импорта файла",
                "verbose_name_plural": "Логи импорта файлов",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="injestjob",
            name="server",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="injest.remoteserver",
                verbose_name="Сервер",
            ),
        ),
    ]
