# Generated by Django 5.2.4 on 2025-07-28 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("slug", models.SlugField(blank=True, unique=True, verbose_name="URL")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активность"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="channel_logos/",
                        verbose_name="Логотип",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "stream_url",
                    models.URLField(
                        max_length=500, verbose_name="Ссылка на стрим (HLS)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Телеканал",
                "verbose_name_plural": "Телеканалы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("start_time", models.DateTimeField(verbose_name="Время начала")),
                ("end_time", models.DateTimeField(verbose_name="Время окончания")),
                (
                    "duration",
                    models.DurationField(editable=False, verbose_name="Длительность"),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="tvchannels.channel",
                        verbose_name="Телеканал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Программа",
                "verbose_name_plural": "Программы",
                "ordering": ["start_time"],
                "indexes": [
                    models.Index(
                        fields=["channel", "start_time"],
                        name="tvchannels_pr_channel_38f738_idx",
                    )
                ],
            },
        ),
    ]
