# Generated by Django 5.2.4 on 2025-07-28 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tvchannels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "file_path",
                    models.CharField(max_length=500, verbose_name="Путь к файлу"),
                ),
                (
                    "extension",
                    models.CharField(
                        choices=[
                            ("mp4", "MP4"),
                            ("avi", "AVI"),
                            ("mkv", "MKV"),
                            ("mov", "MOV"),
                            ("wmv", "WMV"),
                            ("flv", "FLV"),
                            ("webm", "WebM"),
                            ("m4v", "M4V"),
                            ("3gp", "3GP"),
                            ("ts", "TS"),
                        ],
                        max_length=10,
                        verbose_name="Расширение (контейнер)",
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(verbose_name="Длительность (секунды)"),
                ),
                (
                    "duration_frames",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Длительность (кадры)"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveBigIntegerField(verbose_name="Размер файла (байты)"),
                ),
                (
                    "video_bitrate",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Битрейт видео (kbps)"
                    ),
                ),
                (
                    "audio_bitrate",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Битрейт аудио (kbps)"
                    ),
                ),
                (
                    "video_codec",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Видеокодек"
                    ),
                ),
                (
                    "audio_codec",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Аудиокодек"
                    ),
                ),
                (
                    "resolution_width",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Ширина (пиксели)"
                    ),
                ),
                (
                    "resolution_height",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Высота (пиксели)"
                    ),
                ),
                (
                    "framerate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        verbose_name="Частота кадров (fps)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Видеофайл",
                "verbose_name_plural": "Видеофайлы",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["extension"], name="tvchannels_vi_extensi_238b29_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="tvchannels_vi_created_9c1823_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VideoMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Оригинальное название"
                    ),
                ),
                (
                    "series_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Название серии/эпизода",
                    ),
                ),
                (
                    "season_number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Номер сезона"
                    ),
                ),
                (
                    "episode_number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Номер эпизода"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("series", "Сериалы"),
                            ("shows", "Передачи"),
                            ("movies", "Фильмы"),
                            ("documentaries", "Документальные фильмы"),
                            ("news", "Новости"),
                            ("sports", "Спорт"),
                            ("entertainment", "Развлекательные"),
                            ("educational", "Образовательные"),
                            ("children", "Детские"),
                            ("music", "Музыкальные"),
                            ("other", "Прочее"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "age_rating",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("0+", "0+"),
                            ("6+", "6+"),
                            ("12+", "12+"),
                            ("16+", "16+"),
                            ("18+", "18+"),
                        ],
                        max_length=3,
                        verbose_name="Возрастной ценз",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("kk", "Казахский"),
                            ("ru", "Русский"),
                            ("en", "Английский"),
                            ("zh", "Китайский"),
                            ("tr", "Турецкий"),
                            ("fr", "Французский"),
                            ("de", "Немецкий"),
                            ("es", "Испанский"),
                            ("other", "Другой"),
                        ],
                        default="kk",
                        max_length=10,
                        verbose_name="Язык",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "director",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Режиссер"
                    ),
                ),
                (
                    "actors",
                    models.TextField(
                        blank=True, help_text="Через запятую", verbose_name="Актеры"
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Год выпуска"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Страна производства"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Через запятую",
                        max_length=500,
                        verbose_name="Теги",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "video_file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="tvchannels.videofile",
                        verbose_name="Видеофайл",
                    ),
                ),
            ],
            options={
                "verbose_name": "Метаданные видео",
                "verbose_name_plural": "Метаданные видео",
                "indexes": [
                    models.Index(
                        fields=["category"], name="tvchannels_vi_categor_7e8d06_idx"
                    ),
                    models.Index(
                        fields=["language"], name="tvchannels_vi_languag_a698b6_idx"
                    ),
                    models.Index(
                        fields=["age_rating"], name="channels_vi_age_rat_ed4899_idx"
                    ),
                    models.Index(fields=["year"], name="channels_vi_year_887817_idx"),
                ],
            },
        ),
    ]
