# Generated by Django 5.2.4 on 2025-07-28 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tvchannels", "0002_videofile_videometadata"),
    ]

    operations = []
