# Generated by Django 5.2.4 on 2025-07-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tvchannels", "0003_auto_20250728_1935"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videofile",
            name="duration_seconds",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Длительность (секунды)"
            ),
        ),
        migrations.AlterField(
            model_name="videofile",
            name="file_size",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Размер файла (байты)"
            ),
        ),
    ]
