# Generated by Django 5.2.4 on 2025-07-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tvchannels", "0004_alter_videofile_duration_seconds_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="videofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новый"),
                    ("processed", "Обработан"),
                    ("need_add_meta_with_ai", "Требуется добавление метаданных с AI"),
                    ("ai_processing", "Обрабатывается AI"),
                    ("ai_completed", "AI обработка завершена"),
                    ("error", "Ошибка"),
                ],
                default="new",
                max_length=25,
                verbose_name="Статус",
            ),
        ),
    ]
