# Generated by Django 5.2.4 on 2025-07-31 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tvchannels", "0005_videofile_status"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="program",
            new_name="tvchannels__channel_b36793_idx",
            old_name="tvchannels_pr_channel_38f738_idx",
        ),
        migrations.RenameIndex(
            model_name="videofile",
            new_name="tvchannels__extensi_abcdf7_idx",
            old_name="tvchannels_vi_extensi_238b29_idx",
        ),
        migrations.RenameIndex(
            model_name="videofile",
            new_name="tvchannels__created_1f4b48_idx",
            old_name="tvchannels_vi_created_9c1823_idx",
        ),
        migrations.RenameIndex(
            model_name="videometadata",
            new_name="tvchannels__categor_5ee9ed_idx",
            old_name="tvchannels_vi_categor_7e8d06_idx",
        ),
        migrations.RenameIndex(
            model_name="videometadata",
            new_name="tvchannels__languag_10d514_idx",
            old_name="tvchannels_vi_languag_a698b6_idx",
        ),
        migrations.RenameIndex(
            model_name="videometadata",
            new_name="tvchannels__age_rat_ea4d20_idx",
            old_name="channels_vi_age_rat_ed4899_idx",
        ),
        migrations.RenameIndex(
            model_name="videometadata",
            new_name="tvchannels__year_99ae70_idx",
            old_name="channels_vi_year_887817_idx",
        ),
        migrations.AlterField(
            model_name="program",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programs",
                to="tvchannels.channel",
                verbose_name="Телеканал",
            ),
        ),
    ]
