# Generated by Django 5.2.4 on 2025-08-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvchannels', '0006_rename_tvchannels_pr_channel_38f738_idx_tvchannels__channel_b36793_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['-sort_order', 'name'], 'verbose_name': 'Телеканал', 'verbose_name_plural': 'Телеканалы'},
        ),
        migrations.AddField(
            model_name='channel',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Чем больше число — тем выше канал; отрицательные значения отправляют канал в конец', verbose_name='Сортировка'),
        ),
    ]
