# Generated by Django 5.2.4 on 2025-07-29 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tvchannels", "0005_videofile_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="AISettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Ключ настройки"
                    ),
                ),
                ("value", models.TextField(verbose_name="Значение")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Настройка AI",
                "verbose_name_plural": "Настройки AI",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="AIRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        default="generate_title",
                        max_length=50,
                        verbose_name="Тип запроса",
                    ),
                ),
                ("prompt", models.TextField(verbose_name="Промпт для AI")),
                (
                    "response",
                    models.TextField(blank=True, null=True, verbose_name="Ответ AI"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("processing", "Обрабатывается"),
                            ("completed", "Завершен"),
                            ("failed", "Ошибка"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Сообщение об ошибке"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата обработки"
                    ),
                ),
                (
                    "video_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_requests",
                        to="tvchannels.videofile",
                        verbose_name="Видеофайл",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Запрос",
                "verbose_name_plural": "AI Запросы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIProcessingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Информация"),
                            ("warning", "Предупреждение"),
                            ("error", "Ошибка"),
                            ("debug", "Отладка"),
                        ],
                        default="info",
                        max_length=10,
                        verbose_name="Уровень",
                    ),
                ),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "details",
                    models.JSONField(blank=True, null=True, verbose_name="Детали"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "video_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_logs",
                        to="tvchannels.videofile",
                        verbose_name="Видеофайл",
                    ),
                ),
                (
                    "ai_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="ai_metadata.airequest",
                        verbose_name="AI запрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог обработки AI",
                "verbose_name_plural": "Логи обработки AI",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="airequest",
            index=models.Index(fields=["status"], name="ai_metadata_status_1ae95f_idx"),
        ),
        migrations.AddIndex(
            model_name="airequest",
            index=models.Index(
                fields=["video_file", "request_type"],
                name="ai_metadata_video_f_7339e9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="airequest",
            index=models.Index(
                fields=["created_at"], name="ai_metadata_created_8ba101_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiprocessinglog",
            index=models.Index(fields=["level"], name="ai_metadata_level_2f028a_idx"),
        ),
        migrations.AddIndex(
            model_name="aiprocessinglog",
            index=models.Index(
                fields=["video_file"], name="ai_metadata_video_f_002094_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiprocessinglog",
            index=models.Index(
                fields=["created_at"], name="ai_metadata_created_02e81d_idx"
            ),
        ),
    ]
