# Generated by Django 5.2.4 on 2025-07-29 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_metadata", "0001_initial"),
        ("tvchannels", "0005_videofile_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("google", "Google AI"),
                            ("yandex", "Yandex GPT"),
                            ("custom", "Кастомный"),
                        ],
                        max_length=20,
                        verbose_name="Тип провайдера",
                    ),
                ),
                ("api_key", models.TextField(verbose_name="API ключ")),
                (
                    "api_url",
                    models.URLField(
                        blank=True,
                        help_text="Для кастомных провайдеров",
                        verbose_name="URL API",
                    ),
                ),
                (
                    "default_model",
                    models.CharField(
                        max_length=100, verbose_name="Модель по умолчанию"
                    ),
                ),
                (
                    "available_models",
                    models.JSONField(
                        default=list,
                        help_text="Список доступных моделей в формате JSON",
                        verbose_name="Доступные модели",
                    ),
                ),
                (
                    "max_tokens",
                    models.PositiveIntegerField(
                        default=4000, verbose_name="Максимум токенов"
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        default=0.7,
                        help_text="От 0.0 до 2.0",
                        verbose_name="Температура",
                    ),
                ),
                (
                    "timeout",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Таймаут (секунды)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="По умолчанию"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "AI Провайдер",
                "verbose_name_plural": "AI Провайдеры",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AITask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название задачи"
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("generate_title", "Генерация названия"),
                            ("generate_description", "Генерация описания"),
                            ("extract_keywords", "Извлечение ключевых слов"),
                            ("categorize_content", "Категоризация контента"),
                            ("translate_title", "Перевод названия"),
                            ("custom", "Кастомная задача"),
                        ],
                        max_length=30,
                        verbose_name="Тип задачи",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True,
                        help_text="Если не указано, будет использована модель по умолчанию провайдера",
                        max_length=100,
                        verbose_name="Название модели",
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        help_text="Инструкции для AI о том, как выполнять задачу",
                        verbose_name="Системный промпт",
                    ),
                ),
                (
                    "user_prompt_template",
                    models.TextField(
                        help_text="Шаблон с переменными: {file_path}, {filename}, {duration}, {extension}, {file_size}",
                        verbose_name="Шаблон пользовательского промпта",
                    ),
                ),
                (
                    "max_tokens",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Максимум токенов"
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Температура"
                    ),
                ),
                (
                    "response_format",
                    models.CharField(
                        choices=[
                            ("text", "Текст"),
                            ("json", "JSON"),
                            ("structured", "Структурированный"),
                        ],
                        default="text",
                        max_length=50,
                        verbose_name="Формат ответа",
                    ),
                ),
                (
                    "validation_rules",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Правила для проверки ответа AI",
                        verbose_name="Правила валидации",
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Количество повторов"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "is_default_for_type",
                    models.BooleanField(
                        default=False, verbose_name="По умолчанию для типа"
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Больше число = выше приоритет",
                        verbose_name="Приоритет",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "AI Задача",
                "verbose_name_plural": "AI Задачи",
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.RemoveIndex(
            model_name="airequest",
            name="ai_metadata_video_f_7339e9_idx",
        ),
        migrations.AddField(
            model_name="airequest",
            name="cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=10,
                null=True,
                verbose_name="Стоимость",
            ),
        ),
        migrations.AddField(
            model_name="airequest",
            name="execution_time",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Время выполнения (сек)"
            ),
        ),
        migrations.AddField(
            model_name="airequest",
            name="model_used",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Использованная модель",
            ),
        ),
        migrations.AddField(
            model_name="airequest",
            name="retry_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество попыток"
            ),
        ),
        migrations.AddField(
            model_name="airequest",
            name="system_prompt",
            field=models.TextField(
                blank=True, default="", verbose_name="Системный промпт"
            ),
        ),
        migrations.AddField(
            model_name="airequest",
            name="tokens_used",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Использовано токенов"
            ),
        ),
        migrations.AddField(
            model_name="airequest",
            name="user_prompt",
            field=models.TextField(
                blank=True, default="", verbose_name="Пользовательский промпт"
            ),
        ),
        migrations.AlterField(
            model_name="airequest",
            name="prompt",
            field=models.TextField(
                blank=True, default="", verbose_name="Промпт (legacy)"
            ),
        ),
        migrations.AlterField(
            model_name="airequest",
            name="request_type",
            field=models.CharField(
                blank=True,
                default="generate_title",
                max_length=50,
                verbose_name="Тип запроса (legacy)",
            ),
        ),
        migrations.AlterField(
            model_name="airequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает"),
                    ("processing", "Обрабатывается"),
                    ("completed", "Завершен"),
                    ("failed", "Ошибка"),
                    ("cancelled", "Отменен"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AddField(
            model_name="airequest",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to="ai_metadata.aiprovider",
                verbose_name="AI Провайдер",
            ),
        ),
        migrations.AddField(
            model_name="aitask",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                help_text="Если не указан, будет использован провайдер по умолчанию",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="ai_metadata.aiprovider",
                verbose_name="AI Провайдер",
            ),
        ),
        migrations.AddField(
            model_name="airequest",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to="ai_metadata.aitask",
                verbose_name="AI Задача",
            ),
        ),
        migrations.AddIndex(
            model_name="airequest",
            index=models.Index(
                fields=["video_file", "task"], name="ai_metadata_video_f_013e2a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="airequest",
            index=models.Index(
                fields=["task", "status"], name="ai_metadata_task_id_0ae230_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="airequest",
            index=models.Index(
                fields=["provider"], name="ai_metadata_provide_109404_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aitask",
            index=models.Index(
                fields=["task_type", "is_active"], name="ai_metadata_task_ty_940998_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aitask",
            index=models.Index(
                fields=["is_default_for_type", "task_type"],
                name="ai_metadata_is_defa_1f61d2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aitask",
            index=models.Index(
                fields=["priority"], name="ai_metadata_priorit_1f0c72_idx"
            ),
        ),
    ]
